services:
  - type: web
    name: laravel-docker-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    branch: main
    buildCommand: ""
    startCommand: |
      touch /tmp/database.sqlite
      php artisan migrate --force
      apache2-foreground